/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real FORCENLPsolver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

int FORCENLPsolver_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_objective_0_alloc_mem(void);
int FORCENLPsolver_objective_0_init_mem(int mem);
void FORCENLPsolver_objective_0_free_mem(int mem);
int FORCENLPsolver_objective_0_checkout(void);
void FORCENLPsolver_objective_0_release(int mem);
void FORCENLPsolver_objective_0_incref(void);
void FORCENLPsolver_objective_0_decref(void);
casadi_int FORCENLPsolver_objective_0_n_out(void);
casadi_int FORCENLPsolver_objective_0_n_in(void);
casadi_real FORCENLPsolver_objective_0_default_in(casadi_int i);
const char* FORCENLPsolver_objective_0_name_in(casadi_int i);
const char* FORCENLPsolver_objective_0_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_objective_0_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_objective_0_sparsity_out(casadi_int i);
int FORCENLPsolver_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_dobjective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_dobjective_0_alloc_mem(void);
int FORCENLPsolver_dobjective_0_init_mem(int mem);
void FORCENLPsolver_dobjective_0_free_mem(int mem);
int FORCENLPsolver_dobjective_0_checkout(void);
void FORCENLPsolver_dobjective_0_release(int mem);
void FORCENLPsolver_dobjective_0_incref(void);
void FORCENLPsolver_dobjective_0_decref(void);
casadi_int FORCENLPsolver_dobjective_0_n_out(void);
casadi_int FORCENLPsolver_dobjective_0_n_in(void);
casadi_real FORCENLPsolver_dobjective_0_default_in(casadi_int i);
const char* FORCENLPsolver_dobjective_0_name_in(casadi_int i);
const char* FORCENLPsolver_dobjective_0_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_dobjective_0_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_dobjective_0_sparsity_out(casadi_int i);
int FORCENLPsolver_dobjective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_dynamics_0_alloc_mem(void);
int FORCENLPsolver_dynamics_0_init_mem(int mem);
void FORCENLPsolver_dynamics_0_free_mem(int mem);
int FORCENLPsolver_dynamics_0_checkout(void);
void FORCENLPsolver_dynamics_0_release(int mem);
void FORCENLPsolver_dynamics_0_incref(void);
void FORCENLPsolver_dynamics_0_decref(void);
casadi_int FORCENLPsolver_dynamics_0_n_out(void);
casadi_int FORCENLPsolver_dynamics_0_n_in(void);
casadi_real FORCENLPsolver_dynamics_0_default_in(casadi_int i);
const char* FORCENLPsolver_dynamics_0_name_in(casadi_int i);
const char* FORCENLPsolver_dynamics_0_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_dynamics_0_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_dynamics_0_sparsity_out(casadi_int i);
int FORCENLPsolver_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_ddynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_ddynamics_0_alloc_mem(void);
int FORCENLPsolver_ddynamics_0_init_mem(int mem);
void FORCENLPsolver_ddynamics_0_free_mem(int mem);
int FORCENLPsolver_ddynamics_0_checkout(void);
void FORCENLPsolver_ddynamics_0_release(int mem);
void FORCENLPsolver_ddynamics_0_incref(void);
void FORCENLPsolver_ddynamics_0_decref(void);
casadi_int FORCENLPsolver_ddynamics_0_n_out(void);
casadi_int FORCENLPsolver_ddynamics_0_n_in(void);
casadi_real FORCENLPsolver_ddynamics_0_default_in(casadi_int i);
const char* FORCENLPsolver_ddynamics_0_name_in(casadi_int i);
const char* FORCENLPsolver_ddynamics_0_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_ddynamics_0_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_ddynamics_0_sparsity_out(casadi_int i);
int FORCENLPsolver_ddynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_inequalities_0_alloc_mem(void);
int FORCENLPsolver_inequalities_0_init_mem(int mem);
void FORCENLPsolver_inequalities_0_free_mem(int mem);
int FORCENLPsolver_inequalities_0_checkout(void);
void FORCENLPsolver_inequalities_0_release(int mem);
void FORCENLPsolver_inequalities_0_incref(void);
void FORCENLPsolver_inequalities_0_decref(void);
casadi_int FORCENLPsolver_inequalities_0_n_out(void);
casadi_int FORCENLPsolver_inequalities_0_n_in(void);
casadi_real FORCENLPsolver_inequalities_0_default_in(casadi_int i);
const char* FORCENLPsolver_inequalities_0_name_in(casadi_int i);
const char* FORCENLPsolver_inequalities_0_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_inequalities_0_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_inequalities_0_sparsity_out(casadi_int i);
int FORCENLPsolver_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_dinequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_dinequalities_0_alloc_mem(void);
int FORCENLPsolver_dinequalities_0_init_mem(int mem);
void FORCENLPsolver_dinequalities_0_free_mem(int mem);
int FORCENLPsolver_dinequalities_0_checkout(void);
void FORCENLPsolver_dinequalities_0_release(int mem);
void FORCENLPsolver_dinequalities_0_incref(void);
void FORCENLPsolver_dinequalities_0_decref(void);
casadi_int FORCENLPsolver_dinequalities_0_n_out(void);
casadi_int FORCENLPsolver_dinequalities_0_n_in(void);
casadi_real FORCENLPsolver_dinequalities_0_default_in(casadi_int i);
const char* FORCENLPsolver_dinequalities_0_name_in(casadi_int i);
const char* FORCENLPsolver_dinequalities_0_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_dinequalities_0_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_dinequalities_0_sparsity_out(casadi_int i);
int FORCENLPsolver_dinequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_objective_1_alloc_mem(void);
int FORCENLPsolver_objective_1_init_mem(int mem);
void FORCENLPsolver_objective_1_free_mem(int mem);
int FORCENLPsolver_objective_1_checkout(void);
void FORCENLPsolver_objective_1_release(int mem);
void FORCENLPsolver_objective_1_incref(void);
void FORCENLPsolver_objective_1_decref(void);
casadi_int FORCENLPsolver_objective_1_n_out(void);
casadi_int FORCENLPsolver_objective_1_n_in(void);
casadi_real FORCENLPsolver_objective_1_default_in(casadi_int i);
const char* FORCENLPsolver_objective_1_name_in(casadi_int i);
const char* FORCENLPsolver_objective_1_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_objective_1_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_objective_1_sparsity_out(casadi_int i);
int FORCENLPsolver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_dobjective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_dobjective_1_alloc_mem(void);
int FORCENLPsolver_dobjective_1_init_mem(int mem);
void FORCENLPsolver_dobjective_1_free_mem(int mem);
int FORCENLPsolver_dobjective_1_checkout(void);
void FORCENLPsolver_dobjective_1_release(int mem);
void FORCENLPsolver_dobjective_1_incref(void);
void FORCENLPsolver_dobjective_1_decref(void);
casadi_int FORCENLPsolver_dobjective_1_n_out(void);
casadi_int FORCENLPsolver_dobjective_1_n_in(void);
casadi_real FORCENLPsolver_dobjective_1_default_in(casadi_int i);
const char* FORCENLPsolver_dobjective_1_name_in(casadi_int i);
const char* FORCENLPsolver_dobjective_1_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_dobjective_1_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_dobjective_1_sparsity_out(casadi_int i);
int FORCENLPsolver_dobjective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_inequalities_1_alloc_mem(void);
int FORCENLPsolver_inequalities_1_init_mem(int mem);
void FORCENLPsolver_inequalities_1_free_mem(int mem);
int FORCENLPsolver_inequalities_1_checkout(void);
void FORCENLPsolver_inequalities_1_release(int mem);
void FORCENLPsolver_inequalities_1_incref(void);
void FORCENLPsolver_inequalities_1_decref(void);
casadi_int FORCENLPsolver_inequalities_1_n_out(void);
casadi_int FORCENLPsolver_inequalities_1_n_in(void);
casadi_real FORCENLPsolver_inequalities_1_default_in(casadi_int i);
const char* FORCENLPsolver_inequalities_1_name_in(casadi_int i);
const char* FORCENLPsolver_inequalities_1_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_inequalities_1_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_inequalities_1_sparsity_out(casadi_int i);
int FORCENLPsolver_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FORCENLPsolver_dinequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FORCENLPsolver_dinequalities_1_alloc_mem(void);
int FORCENLPsolver_dinequalities_1_init_mem(int mem);
void FORCENLPsolver_dinequalities_1_free_mem(int mem);
int FORCENLPsolver_dinequalities_1_checkout(void);
void FORCENLPsolver_dinequalities_1_release(int mem);
void FORCENLPsolver_dinequalities_1_incref(void);
void FORCENLPsolver_dinequalities_1_decref(void);
casadi_int FORCENLPsolver_dinequalities_1_n_out(void);
casadi_int FORCENLPsolver_dinequalities_1_n_in(void);
casadi_real FORCENLPsolver_dinequalities_1_default_in(casadi_int i);
const char* FORCENLPsolver_dinequalities_1_name_in(casadi_int i);
const char* FORCENLPsolver_dinequalities_1_name_out(casadi_int i);
const casadi_int* FORCENLPsolver_dinequalities_1_sparsity_in(casadi_int i);
const casadi_int* FORCENLPsolver_dinequalities_1_sparsity_out(casadi_int i);
int FORCENLPsolver_dinequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
