/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCES_NLP_solver_model_ ## ID
#endif

#include <math.h> 
#include "FORCES_NLP_solver_model.h"

#ifndef casadi_real
#define casadi_real FORCES_NLP_solver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[13] = {1, 8, 0, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[38] = {6, 8, 0, 4, 10, 11, 12, 17, 19, 21, 27, 0, 1, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 0, 1, 2, 3, 4, 0, 3, 1, 4, 0, 1, 2, 3, 4, 5};

/* FORCES_NLP_solver_objective_0:(i0[8],i1[0])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=10.;
  a1=arg[0]? arg[0][2] : 0;
  a2=5.0000000000000000e-01;
  a1=(a1-a2);
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a3=arg[0]? arg[0][3] : 0;
  a3=(a3-a2);
  a3=casadi_sq(a3);
  a0=(a0*a3);
  a1=(a1+a0);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

int FORCES_NLP_solver_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCES_NLP_solver_objective_0_alloc_mem(void) {
  return 0;
}

int FORCES_NLP_solver_objective_0_init_mem(int mem) {
  return 0;
}

void FORCES_NLP_solver_objective_0_free_mem(int mem) {
}

int FORCES_NLP_solver_objective_0_checkout(void) {
  return 0;
}

void FORCES_NLP_solver_objective_0_release(int mem) {
}

void FORCES_NLP_solver_objective_0_incref(void) {
}

void FORCES_NLP_solver_objective_0_decref(void) {
}

casadi_int FORCES_NLP_solver_objective_0_n_in(void) { return 2;}

casadi_int FORCES_NLP_solver_objective_0_n_out(void) { return 1;}

casadi_real FORCES_NLP_solver_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCES_NLP_solver_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCES_NLP_solver_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCES_NLP_solver_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_dobjective_0:(i0[8],i1[0])->(o0[1x8,2nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=10.;
  a1=arg[0]? arg[0][2] : 0;
  a2=5.0000000000000000e-01;
  a1=(a1-a2);
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][3] : 0;
  a1=(a1-a2);
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

int FORCES_NLP_solver_dobjective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCES_NLP_solver_dobjective_0_alloc_mem(void) {
  return 0;
}

int FORCES_NLP_solver_dobjective_0_init_mem(int mem) {
  return 0;
}

void FORCES_NLP_solver_dobjective_0_free_mem(int mem) {
}

int FORCES_NLP_solver_dobjective_0_checkout(void) {
  return 0;
}

void FORCES_NLP_solver_dobjective_0_release(int mem) {
}

void FORCES_NLP_solver_dobjective_0_incref(void) {
}

void FORCES_NLP_solver_dobjective_0_decref(void) {
}

casadi_int FORCES_NLP_solver_dobjective_0_n_in(void) { return 2;}

casadi_int FORCES_NLP_solver_dobjective_0_n_out(void) { return 1;}

casadi_real FORCES_NLP_solver_dobjective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCES_NLP_solver_dobjective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCES_NLP_solver_dobjective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_dobjective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_dobjective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

int FORCES_NLP_solver_dobjective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_dynamics_0:(i0[8],i1[0])->(o0[6]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=1.6666666666666668e-03;
  a2=arg[0]? arg[0][5] : 0;
  a3=2.;
  a4=5.0000000000000001e-03;
  a5=arg[0]? arg[0][0] : 0;
  a6=2.9999999999999999e-02;
  a7=(a5/a6);
  a8=arg[0]? arg[0][4] : 0;
  a9=sin(a8);
  a7=(a7*a9);
  a9=(a4*a7);
  a9=(a2-a9);
  a9=(a3*a9);
  a9=(a2+a9);
  a10=(a5/a6);
  a11=arg[0]? arg[0][7] : 0;
  a12=(a4*a11);
  a12=(a8+a12);
  a13=sin(a12);
  a10=(a10*a13);
  a13=(a4*a10);
  a13=(a2-a13);
  a13=(a3*a13);
  a9=(a9+a13);
  a13=1.0000000000000000e-02;
  a14=(a5/a6);
  a15=arg[0]? arg[0][1] : 0;
  a16=1.4300000000000000e-05;
  a17=(a15/a16);
  a18=(a4*a17);
  a18=(a11+a18);
  a19=(a4*a18);
  a19=(a8+a19);
  a20=sin(a19);
  a14=(a14*a20);
  a20=(a13*a14);
  a20=(a2-a20);
  a9=(a9+a20);
  a9=(a1*a9);
  a0=(a0+a9);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a9=arg[0]? arg[0][6] : 0;
  a20=-9.8100000000000005e+00;
  a21=(a5/a6);
  a22=cos(a8);
  a21=(a21*a22);
  a21=(a20+a21);
  a22=(a4*a21);
  a22=(a9+a22);
  a22=(a3*a22);
  a22=(a9+a22);
  a23=(a5/a6);
  a12=cos(a12);
  a23=(a23*a12);
  a23=(a20+a23);
  a12=(a4*a23);
  a12=(a9+a12);
  a12=(a3*a12);
  a22=(a22+a12);
  a12=(a5/a6);
  a19=cos(a19);
  a12=(a12*a19);
  a12=(a20+a12);
  a19=(a13*a12);
  a19=(a9+a19);
  a22=(a22+a19);
  a22=(a1*a22);
  a0=(a0+a22);
  if (res[0]!=0) res[0][1]=a0;
  a18=(a3*a18);
  a18=(a11+a18);
  a0=(a15/a16);
  a4=(a4*a0);
  a4=(a11+a4);
  a22=(a3*a4);
  a18=(a18+a22);
  a22=(a15/a16);
  a19=(a13*a22);
  a19=(a11+a19);
  a18=(a18+a19);
  a18=(a1*a18);
  a18=(a8+a18);
  if (res[0]!=0) res[0][2]=a18;
  a10=(a3*a10);
  a7=(a7+a10);
  a14=(a3*a14);
  a7=(a7+a14);
  a14=(a5/a6);
  a13=(a13*a4);
  a8=(a8+a13);
  a13=sin(a8);
  a14=(a14*a13);
  a7=(a7+a14);
  a7=(a1*a7);
  a2=(a2-a7);
  if (res[0]!=0) res[0][3]=a2;
  a23=(a3*a23);
  a21=(a21+a23);
  a12=(a3*a12);
  a21=(a21+a12);
  a5=(a5/a6);
  a8=cos(a8);
  a5=(a5*a8);
  a20=(a20+a5);
  a21=(a21+a20);
  a21=(a1*a21);
  a9=(a9+a21);
  if (res[0]!=0) res[0][4]=a9;
  a0=(a3*a0);
  a17=(a17+a0);
  a3=(a3*a22);
  a17=(a17+a3);
  a15=(a15/a16);
  a17=(a17+a15);
  a1=(a1*a17);
  a11=(a11+a1);
  if (res[0]!=0) res[0][5]=a11;
  return 0;
}

int FORCES_NLP_solver_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCES_NLP_solver_dynamics_0_alloc_mem(void) {
  return 0;
}

int FORCES_NLP_solver_dynamics_0_init_mem(int mem) {
  return 0;
}

void FORCES_NLP_solver_dynamics_0_free_mem(int mem) {
}

int FORCES_NLP_solver_dynamics_0_checkout(void) {
  return 0;
}

void FORCES_NLP_solver_dynamics_0_release(int mem) {
}

void FORCES_NLP_solver_dynamics_0_incref(void) {
}

void FORCES_NLP_solver_dynamics_0_decref(void) {
}

casadi_int FORCES_NLP_solver_dynamics_0_n_in(void) { return 2;}

casadi_int FORCES_NLP_solver_dynamics_0_n_out(void) { return 1;}

casadi_real FORCES_NLP_solver_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCES_NLP_solver_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCES_NLP_solver_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

int FORCES_NLP_solver_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_ddynamics_0:(i0[8],i1[0])->(o0[6x8,27nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=1.6666666666666668e-03;
  a1=2.;
  a2=5.0000000000000001e-03;
  a3=3.3333333333333336e+01;
  a4=arg[0]? arg[0][4] : 0;
  a5=sin(a4);
  a5=(a3*a5);
  a6=(a2*a5);
  a6=(a1*a6);
  a7=arg[0]? arg[0][7] : 0;
  a8=(a2*a7);
  a8=(a4+a8);
  a9=sin(a8);
  a9=(a3*a9);
  a10=(a2*a9);
  a10=(a1*a10);
  a6=(a6+a10);
  a10=1.0000000000000000e-02;
  a11=arg[0]? arg[0][1] : 0;
  a12=1.4300000000000000e-05;
  a13=(a11/a12);
  a13=(a2*a13);
  a13=(a7+a13);
  a13=(a2*a13);
  a13=(a4+a13);
  a14=sin(a13);
  a14=(a3*a14);
  a15=(a10*a14);
  a6=(a6+a15);
  a6=(a0*a6);
  a6=(-a6);
  if (res[0]!=0) res[0][0]=a6;
  a6=cos(a4);
  a6=(a3*a6);
  a15=(a2*a6);
  a15=(a1*a15);
  a16=cos(a8);
  a16=(a3*a16);
  a17=(a2*a16);
  a17=(a1*a17);
  a15=(a15+a17);
  a17=cos(a13);
  a17=(a3*a17);
  a18=(a10*a17);
  a15=(a15+a18);
  a15=(a0*a15);
  if (res[0]!=0) res[0][1]=a15;
  a9=(a1*a9);
  a5=(a5+a9);
  a14=(a1*a14);
  a5=(a5+a14);
  a11=(a11/a12);
  a11=(a2*a11);
  a7=(a7+a11);
  a7=(a10*a7);
  a7=(a4+a7);
  a11=sin(a7);
  a11=(a3*a11);
  a5=(a5+a11);
  a5=(a0*a5);
  a5=(-a5);
  if (res[0]!=0) res[0][2]=a5;
  a16=(a1*a16);
  a6=(a6+a16);
  a17=(a1*a17);
  a6=(a6+a17);
  a17=cos(a7);
  a3=(a3*a17);
  a6=(a6+a3);
  a6=(a0*a6);
  if (res[0]!=0) res[0][3]=a6;
  a6=arg[0]? arg[0][0] : 0;
  a3=2.9999999999999999e-02;
  a17=(a6/a3);
  a16=1.7482517482517483e+00;
  a5=cos(a13);
  a11=(a16*a5);
  a11=(a17*a11);
  a12=(a10*a11);
  a12=(a0*a12);
  a12=(-a12);
  if (res[0]!=0) res[0][4]=a12;
  a12=(a6/a3);
  a13=sin(a13);
  a16=(a16*a13);
  a16=(a12*a16);
  a14=(a10*a16);
  a14=(a0*a14);
  a14=(-a14);
  if (res[0]!=0) res[0][5]=a14;
  a14=3.4965034965034967e+00;
  if (res[0]!=0) res[0][6]=a14;
  a11=(a1*a11);
  a9=(a6/a3);
  a15=cos(a7);
  a18=(a14*a15);
  a18=(a9*a18);
  a11=(a11+a18);
  a11=(a0*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][7]=a11;
  a16=(a1*a16);
  a11=(a6/a3);
  a7=sin(a7);
  a14=(a14*a7);
  a14=(a11*a14);
  a16=(a16+a14);
  a16=(a0*a16);
  a16=(-a16);
  if (res[0]!=0) res[0][8]=a16;
  a16=6.9930069930069953e+02;
  if (res[0]!=0) res[0][9]=a16;
  a16=1.;
  if (res[0]!=0) res[0][10]=a16;
  if (res[0]!=0) res[0][11]=a16;
  a14=(a6/a3);
  a18=cos(a4);
  a14=(a14*a18);
  a18=(a2*a14);
  a18=(a1*a18);
  a19=(a6/a3);
  a20=cos(a8);
  a21=(a19*a20);
  a22=(a2*a21);
  a22=(a1*a22);
  a18=(a18+a22);
  a22=(a17*a5);
  a23=(a10*a22);
  a18=(a18+a23);
  a18=(a0*a18);
  a18=(-a18);
  if (res[0]!=0) res[0][12]=a18;
  a18=(a6/a3);
  a4=sin(a4);
  a18=(a18*a4);
  a4=(a2*a18);
  a4=(a1*a4);
  a6=(a6/a3);
  a8=sin(a8);
  a3=(a6*a8);
  a23=(a2*a3);
  a23=(a1*a23);
  a4=(a4+a23);
  a23=(a12*a13);
  a24=(a10*a23);
  a4=(a4+a24);
  a4=(a0*a4);
  a4=(-a4);
  if (res[0]!=0) res[0][13]=a4;
  if (res[0]!=0) res[0][14]=a16;
  a21=(a1*a21);
  a14=(a14+a21);
  a22=(a1*a22);
  a14=(a14+a22);
  a22=(a9*a15);
  a14=(a14+a22);
  a14=(a0*a14);
  a14=(-a14);
  if (res[0]!=0) res[0][15]=a14;
  a3=(a1*a3);
  a18=(a18+a3);
  a23=(a1*a23);
  a18=(a18+a23);
  a23=(a11*a7);
  a18=(a18+a23);
  a18=(a0*a18);
  a18=(-a18);
  if (res[0]!=0) res[0][16]=a18;
  if (res[0]!=0) res[0][17]=a10;
  if (res[0]!=0) res[0][18]=a16;
  if (res[0]!=0) res[0][19]=a10;
  if (res[0]!=0) res[0][20]=a16;
  a20=(a2*a20);
  a19=(a19*a20);
  a20=(a2*a19);
  a20=(a1*a20);
  a5=(a2*a5);
  a17=(a17*a5);
  a5=(a10*a17);
  a20=(a20+a5);
  a20=(a0*a20);
  a20=(-a20);
  if (res[0]!=0) res[0][21]=a20;
  a8=(a2*a8);
  a6=(a6*a8);
  a8=(a2*a6);
  a8=(a1*a8);
  a2=(a2*a13);
  a12=(a12*a2);
  a2=(a10*a12);
  a8=(a8+a2);
  a8=(a0*a8);
  a8=(-a8);
  if (res[0]!=0) res[0][22]=a8;
  if (res[0]!=0) res[0][23]=a10;
  a19=(a1*a19);
  a17=(a1*a17);
  a19=(a19+a17);
  a15=(a10*a15);
  a9=(a9*a15);
  a19=(a19+a9);
  a19=(a0*a19);
  a19=(-a19);
  if (res[0]!=0) res[0][24]=a19;
  a6=(a1*a6);
  a1=(a1*a12);
  a6=(a6+a1);
  a10=(a10*a7);
  a11=(a11*a10);
  a6=(a6+a11);
  a0=(a0*a6);
  a0=(-a0);
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a16;
  return 0;
}

int FORCES_NLP_solver_ddynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCES_NLP_solver_ddynamics_0_alloc_mem(void) {
  return 0;
}

int FORCES_NLP_solver_ddynamics_0_init_mem(int mem) {
  return 0;
}

void FORCES_NLP_solver_ddynamics_0_free_mem(int mem) {
}

int FORCES_NLP_solver_ddynamics_0_checkout(void) {
  return 0;
}

void FORCES_NLP_solver_ddynamics_0_release(int mem) {
}

void FORCES_NLP_solver_ddynamics_0_incref(void) {
}

void FORCES_NLP_solver_ddynamics_0_decref(void) {
}

casadi_int FORCES_NLP_solver_ddynamics_0_n_in(void) { return 2;}

casadi_int FORCES_NLP_solver_ddynamics_0_n_out(void) { return 1;}

casadi_real FORCES_NLP_solver_ddynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCES_NLP_solver_ddynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCES_NLP_solver_ddynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_ddynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_ddynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

int FORCES_NLP_solver_ddynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_objective_1:(i0[8],i1[0])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=10.;
  a1=arg[0]? arg[0][2] : 0;
  a2=5.0000000000000000e-01;
  a1=(a1-a2);
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a3=arg[0]? arg[0][3] : 0;
  a3=(a3-a2);
  a3=casadi_sq(a3);
  a0=(a0*a3);
  a1=(a1+a0);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

int FORCES_NLP_solver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCES_NLP_solver_objective_1_alloc_mem(void) {
  return 0;
}

int FORCES_NLP_solver_objective_1_init_mem(int mem) {
  return 0;
}

void FORCES_NLP_solver_objective_1_free_mem(int mem) {
}

int FORCES_NLP_solver_objective_1_checkout(void) {
  return 0;
}

void FORCES_NLP_solver_objective_1_release(int mem) {
}

void FORCES_NLP_solver_objective_1_incref(void) {
}

void FORCES_NLP_solver_objective_1_decref(void) {
}

casadi_int FORCES_NLP_solver_objective_1_n_in(void) { return 2;}

casadi_int FORCES_NLP_solver_objective_1_n_out(void) { return 1;}

casadi_real FORCES_NLP_solver_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCES_NLP_solver_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCES_NLP_solver_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCES_NLP_solver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_dobjective_1:(i0[8],i1[0])->(o0[1x8,2nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=10.;
  a1=arg[0]? arg[0][2] : 0;
  a2=5.0000000000000000e-01;
  a1=(a1-a2);
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][3] : 0;
  a1=(a1-a2);
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

int FORCES_NLP_solver_dobjective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int FORCES_NLP_solver_dobjective_1_alloc_mem(void) {
  return 0;
}

int FORCES_NLP_solver_dobjective_1_init_mem(int mem) {
  return 0;
}

void FORCES_NLP_solver_dobjective_1_free_mem(int mem) {
}

int FORCES_NLP_solver_dobjective_1_checkout(void) {
  return 0;
}

void FORCES_NLP_solver_dobjective_1_release(int mem) {
}

void FORCES_NLP_solver_dobjective_1_incref(void) {
}

void FORCES_NLP_solver_dobjective_1_decref(void) {
}

casadi_int FORCES_NLP_solver_dobjective_1_n_in(void) { return 2;}

casadi_int FORCES_NLP_solver_dobjective_1_n_out(void) { return 1;}

casadi_real FORCES_NLP_solver_dobjective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCES_NLP_solver_dobjective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCES_NLP_solver_dobjective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_dobjective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCES_NLP_solver_dobjective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

int FORCES_NLP_solver_dobjective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
